[package]
name = "eg-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.6.2"
embedded-graphics-simulator = "0.2.1"
wio_splash = { "path" = "../wio_splash" }
